### ISSUE TITLE
_SCN_CreateComboBox

### ISSUE THREAD

**Issue by tonybonykony** [SCNet-Dev/AutoIt-GUI#1]
Dear SCNet, i try to make comboxbox and add some items, but when i click, it doesn't work. Can you give me a example ?
my code : 
$Combo1 = _SCN_CreateComboBox("ComboBox 1",50,50,120,34)
_SCN_ComboBoxMenu("Item1|Item 2|Item 3",$Form1,$Combo1)

**Comment by Hawk63** [comment]
Hi,
The combobox use gui button in order to simulate a combobox. It's not perfect for the moment because it's under developpement (when i have time).

In order to use the combobox you need to :
- Create the first combobox with _SCN_CreateComboBox
- Affect the items, show the menu and return the selection with _SCN_ComboBoxMenu
- Delete the first Combobox
- Create the new Combobox with the item selected as defaut

Code example (change "#include "..\SCNetGUI_UDF.au3" with the good location for you)
[https://github.com/SCNet-Dev/AutoIt-GUI/blob/master/Exemple/ComboBox.au3](url)
